#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GREENHOUSE_DIR="$ROOT_DIR/Greenhouse"
OUT_ROOT="${OUT_ROOT:-$ROOT_DIR/thesis/evidence}"
STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)}"
OUT_DIR="$OUT_ROOT/$STAMP"
MQTT_SECONDS="${MQTT_SECONDS:-25}"
DASHBOARD_URL="${DASHBOARD_URL:-http://localhost}"

usage() {
  cat <<'EOF'
Usage:
  bash thesis/collect_evidence.sh [--start] [--no-mqtt] [--no-export]

Environment:
  OUT_ROOT        Output root, default thesis/evidence
  STAMP           Evidence folder name, default current timestamp
  MQTT_SECONDS    Seconds to listen to greenhouse/#, default 25
  DASHBOARD_URL   Dashboard base URL, default http://localhost

What it collects:
  - docker compose service state and logs
  - MQTT sample from greenhouse/#
  - SQLite counts and latest rows from sensor_log and relay_log
  - CSV exports from dashboard API
  - a README with manual screenshot slots for the defense deck
EOF
}

START_STACK=0
CAPTURE_MQTT=1
CAPTURE_EXPORTS=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --start)
      START_STACK=1
      shift
      ;;
    --no-mqtt)
      CAPTURE_MQTT=0
      shift
      ;;
    --no-export)
      CAPTURE_EXPORTS=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    exit 1
  fi
}

run_capture() {
  local title="$1"
  local file="$2"
  shift 2
  {
    echo "# $title"
    echo "# captured_at=$(date -Iseconds)"
    echo "# command=$*"
    echo
    "$@"
  } > "$file" 2>&1 || {
    local status=$?
    echo "# command_failed status=$status" >> "$file"
    return "$status"
  }
}

require_cmd docker
require_cmd curl

if [[ ! -f "$GREENHOUSE_DIR/docker-compose.yml" ]]; then
  echo "Greenhouse docker-compose.yml not found: $GREENHOUSE_DIR" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

cat > "$OUT_DIR/README.md" <<EOF
# Evidence pack $STAMP

Generated by \`thesis/collect_evidence.sh\`.

## Captured files

| File | Meaning |
|---|---|
| \`docker_ps.txt\` | Container state |
| \`dashboard_logs.txt\` | Last dashboard logs |
| \`mosquitto_logs.txt\` | Last MQTT broker logs |
| \`mqtt_greenhouse_sample.txt\` | Sample from \`greenhouse/#\` |
| \`sqlite_counts.txt\` | Row counts in \`sensor_log\` and \`relay_log\` |
| \`sqlite_sensor_latest.txt\` | Latest sensor rows |
| \`sqlite_relay_latest.txt\` | Latest relay rows |
| \`greenhouse_sensors.csv\` | Sensor export from dashboard API |
| \`greenhouse_relays.csv\` | Relay export from dashboard API |

## Manual screenshots to add

Save screenshots into this folder using these names:

1. \`dashboard_main.png\` - main dashboard after login.
2. \`dashboard_rules.png\` - rules page.
3. \`dashboard_profiles.png\` - profiles page.
4. \`dashboard_stats.png\` - stats/history page.
5. \`relay_toggle.png\` - relay state after a manual toggle.

These files are intended for \`thesis/defense_presentation.pptx\`, chapter 3 and appendices.
EOF

pushd "$GREENHOUSE_DIR" >/dev/null

if [[ "$START_STACK" -eq 1 ]]; then
  MQTT_PORT="${MQTT_PORT:-1883}" docker compose up -d mosquitto dashboard
fi

run_capture "docker compose ps" "$OUT_DIR/docker_ps.txt" docker compose ps || true
run_capture "dashboard logs" "$OUT_DIR/dashboard_logs.txt" docker compose logs --tail=160 dashboard || true
run_capture "mosquitto logs" "$OUT_DIR/mosquitto_logs.txt" docker compose logs --tail=160 mosquitto || true

if [[ "$CAPTURE_MQTT" -eq 1 ]]; then
  {
    echo "# MQTT greenhouse/# sample"
    echo "# captured_at=$(date -Iseconds)"
    echo "# duration_seconds=$MQTT_SECONDS"
    echo
    docker compose exec -T mosquitto sh -lc "timeout $MQTT_SECONDS mosquitto_sub -t 'greenhouse/#' -v" || true
  } > "$OUT_DIR/mqtt_greenhouse_sample.txt" 2>&1
fi

run_capture "SQLite table counts" "$OUT_DIR/sqlite_counts.txt" docker compose exec -T dashboard python - <<'PY' || true
import sqlite3
conn = sqlite3.connect('/data/history.db')
for table in ['sensor_log', 'relay_log']:
    count, = conn.execute(f'select count(*) from {table}').fetchone()
    print(f'{table}\t{count}')
PY

run_capture "Latest sensor rows" "$OUT_DIR/sqlite_sensor_latest.txt" docker compose exec -T dashboard python - <<'PY' || true
import sqlite3
conn = sqlite3.connect('/data/history.db')
for row in conn.execute('select ts, device, temperature, humidity, co2 from sensor_log order by id desc limit 10'):
    print(row)
PY

run_capture "Latest relay rows" "$OUT_DIR/sqlite_relay_latest.txt" docker compose exec -T dashboard python - <<'PY' || true
import sqlite3
conn = sqlite3.connect('/data/history.db')
for row in conn.execute('select ts, relay_id, state from relay_log order by id desc limit 10'):
    print(row)
PY

popd >/dev/null

if [[ "$CAPTURE_EXPORTS" -eq 1 ]]; then
  curl -fsSL "$DASHBOARD_URL/api/export/sensors?format=csv&limit=200" -o "$OUT_DIR/greenhouse_sensors.csv" || true
  curl -fsSL "$DASHBOARD_URL/api/export/relays?format=csv&limit=200" -o "$OUT_DIR/greenhouse_relays.csv" || true
fi

cat <<EOF
Evidence pack written to:
$OUT_DIR

Next manual step:
Open $DASHBOARD_URL, sign in, and save screenshots listed in $OUT_DIR/README.md.
EOF
